name: infralens
description: "InfraLens - AI-powered DevOps monitoring dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  provider: ^6.1.5+1
  web_socket_channel: ^3.0.3
  http: ^1.6.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  intl: ^0.19.0
  timeago: ^3.6.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
